### ISSUE TITLE
[S] Make the theme plot show all of the themes when score is high

### ISSUE THREAD

**Issue by saanahyttinen** [kanerv/TuukkaSaanaKanerva#61] opened 2021-02-28 09:44 UTC
At the moment when searching with for example 'woman' some theme scores get higher, which takes space from the plot and causes the theme words not to be fully visible in the plot.

**Comment by kanerv** [comment] 2021-02-28 19:43
@saanahyttinen do you mean that the labels on the theme plot are overlapping? I did some test searches and I'm not sure if the issue is related to the number of themes, but maybe the length of the names of the themes?

I added some screenshots to clarify, but in short, I did two wildcard searches for _woman_ and _and_. Both of them have ten themes, but the labels are a little off only in _woman_. Maybe this could be fixed by adding more room for labels in the plot itself, although there is already quite a bit of white space around the bars.

<img width="1443" alt="Screenshot 2021-02-28 at 21 37 16" src="https://user-images.githubusercontent.com/77584213/109431179-d9aba380-7a0d-11eb-86d5-009049dff408.png">

<img width="1443" alt="Screenshot 2021-02-28 at 21 33 58" src="https://user-images.githubusercontent.com/77584213/109431182-ddd7c100-7a0d-11eb-966a-f380cdcd5bc3.png">

OR this happens because of something different! 😆  I honestly have no idea

**Comment by saanahyttinen** [comment] 2021-02-28 19:58
For me the problem was that the names of the themes were partly cut out of the picture when the bars were higher, but it doesn’t seem to bee a problem on your screenshots! May be that it was just cause my browser window was not fully open then etc.! I’ll check when i get to my computer! :)

**Comment by saanahyttinen** [comment] 2021-02-28 20:16
![Screenshot 2021-02-28 at 22 14 04](https://user-images.githubusercontent.com/45658192/109432117-66f0f700-7a12-11eb-9875-5d18a9c34c36.png)

This is what it looks like for me! But since it doesn't seem to be problem for everyone I don't think we need to worry about it too much :)

**Closed as completed** 2021-03-03 16:46 UTC
